// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9kBQm9HPwdG42RJk-0npFmZ6ziafs7Cc',
    appId: '1:166779339384:web:cdea6abd76a8f5435a238d',
    messagingSenderId: '166779339384',
    projectId: 'fixar-76ef6',
    authDomain: 'fixar-76ef6.firebaseapp.com',
    storageBucket: 'fixar-76ef6.firebasestorage.app',
    measurementId: 'G-YSHG97RBV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdC50KD2SMv9ss_dHsA_Yv1vCoyp8HwI8',
    appId: '1:166779339384:android:f5ee15a3ea9d395c5a238d',
    messagingSenderId: '166779339384',
    projectId: 'fixar-76ef6',
    storageBucket: 'fixar-76ef6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1TzIvzcJTwZIncTvIhWy96GlWgBaDTVA',
    appId: '1:166779339384:ios:90981bd8dbb954735a238d',
    messagingSenderId: '166779339384',
    projectId: 'fixar-76ef6',
    storageBucket: 'fixar-76ef6.firebasestorage.app',
    iosBundleId: 'com.example.fixAr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1TzIvzcJTwZIncTvIhWy96GlWgBaDTVA',
    appId: '1:166779339384:ios:90981bd8dbb954735a238d',
    messagingSenderId: '166779339384',
    projectId: 'fixar-76ef6',
    storageBucket: 'fixar-76ef6.firebasestorage.app',
    iosBundleId: 'com.example.fixAr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9kBQm9HPwdG42RJk-0npFmZ6ziafs7Cc',
    appId: '1:166779339384:web:dc1c0f47939eaa665a238d',
    messagingSenderId: '166779339384',
    projectId: 'fixar-76ef6',
    authDomain: 'fixar-76ef6.firebaseapp.com',
    storageBucket: 'fixar-76ef6.firebasestorage.app',
    measurementId: 'G-FEDHZPWKBY',
  );
}